"""Tasks Manager

Revision ID: 13aca467dfe4
Revises: 9319c701c809
Create Date: 2023-10-12 14:52:27.321190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13aca467dfe4'
down_revision = '9319c701c809'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
